name: Build EXE

on:
  push:
    tags:
      - 'v*' # jalan kalau ada tag misalnya v1.0, v2.0 dll

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --noconsole --name "LaptopTimer" LaptopTimerTray.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LaptopTimer-exe
          path: dist/LaptopTimer/LaptopTimer.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: LaptopTimer-exe
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: LaptopTimer.exe
        env:
          GITHUB_TOKEN: ${{ github.token }}
